from pathlib import Path
from utils import log, save_output, mark_done, is_done

MODULE = "dorking"

DORK_TEMPLATES = [
    # General
    "site:{domain}",
    "site:{domain} inurl:admin",
    "site:{domain} inurl:login",
    "site:{domain} inurl:dashboard",
    "site:{domain} inurl:panel",
    "site:{domain} inurl:portal",
    "site:{domain} inurl:config",
    "site:{domain} inurl:backup",
    "site:{domain} inurl:test",
    "site:{domain} inurl:dev",
    "site:{domain} inurl:staging",
    "site:{domain} inurl:api",

    # File types
    "site:{domain} filetype:pdf",
    "site:{domain} filetype:doc OR filetype:docx",
    "site:{domain} filetype:xls OR filetype:xlsx",
    "site:{domain} filetype:txt",
    "site:{domain} filetype:env",
    "site:{domain} filetype:sql",
    "site:{domain} filetype:log",
    "site:{domain} filetype:bak",
    "site:{domain} filetype:conf",
    "site:{domain} filetype:xml",
    "site:{domain} filetype:json",
    "site:{domain} filetype:yaml OR filetype:yml",

    # Sensitive exposure
    "site:{domain} intitle:\"index of\"",
    "site:{domain} intitle:\"phpinfo\"",
    "site:{domain} intitle:\"apache status\"",
    "site:{domain} \"error\" OR \"exception\" OR \"stack trace\"",
    "site:{domain} \"password\" OR \"passwd\" OR \"pwd\"",
    "site:{domain} \"api_key\" OR \"apikey\" OR \"api key\"",
    "site:{domain} \"secret\" OR \"token\" OR \"private key\"",
    "site:{domain} \"DB_PASSWORD\" OR \"database_password\"",

    # GitHub
    "site:github.com \"{domain}\"",
    "site:github.com \"{domain}\" password",
    "site:github.com \"{domain}\" secret",
    "site:github.com \"{domain}\" api_key",
    "site:github.com \"{domain}\" token",
    "site:github.com \"{domain}\" config",

    # Subdomains and infrastructure
    "site:pastebin.com \"{domain}\"",
    "site:trello.com \"{domain}\"",
    "site:jira.{domain}",
    "site:confluence.{domain}",
    "site:jenkins.{domain}",
    "site:gitlab.{domain}",
]


def run(domain: str, output_dir: Path, profile: dict, scope: list):
    if is_done(output_dir, MODULE):
        log(output_dir, f"[{MODULE}] Already completed. Skipping.", "WARNING")
        return

    log(output_dir, f"[dorking] Generating dork queries for {domain}")

    dorks = [template.replace("{domain}", domain) for template in DORK_TEMPLATES]
    output = f"# Google/GitHub Dork Queries for {domain}\n"
    output += f"# Generated by ReconFlow\n"
    output += f"# Run these manually in your browser\n\n"

    sections = {
        "General Navigation": dorks[:12],
        "File Type Discovery": dorks[12:24],
        "Sensitive Exposure": dorks[24:32],
        "GitHub Recon": dorks[32:37],
        "Infrastructure": dorks[37:],
    }

    for section, section_dorks in sections.items():
        output += f"\n## {section}\n"
        for dork in section_dorks:
            output += f"{dork}\n"

    save_output(output_dir, "dorks.txt", output)
    log(output_dir, f"[dorking] {len(dorks)} dork queries saved to dorks.txt", "SUCCESS")

    mark_done(output_dir, MODULE)
